### PR TITLE
fix: mana purchases pending forever

### LINKED ISSUE #331: [MoonPay] Purchases with pending status forever
1. Open Buy MANA Modal
2. Select MoonPay
3. Complete the purchase
4. Go back to Decentraland
5. Close the tab while the Purchase is still in progress

When you open a new tab, you will see the modal with status pending forever because the process to check the order status was stopped when the user closed the tab.

### PR DESCRIPTION
**Pull request by kevinszuchet**
Closes #331

### CODE REVIEW

File: src/modules/manaFiatGateway/reducer.ts [hunk 1]
```diff
@@ -111,6 +117,20 @@ export function manaFiatGatewayReducer(
         }
       }
     }
+    case UNSET_PURCHASE: {
```
Comment (fzavalia) [inline src/modules/manaFiatGateway/reducer.ts:120]: Add a test for the unset

File: src/modules/manaFiatGateway/sagas.ts [hunk 2]
```diff
@@ -138,16 +147,40 @@ function* upsertPurchase(
   yield put(setPurchase(purchase))
 }
 
+function* handleStorageLoad() {
```
Comment (fzavalia) [inline src/modules/manaFiatGateway/sagas.ts:150]: Add a test for the saga

File: src/modules/mana/actions.ts [hunk 3]
```diff
@@ -6,3 +6,9 @@ export const SET_PURCHASE = 'Set Purchase'
 export const setPurchase = (purchase: Purchase) =>
   action(SET_PURCHASE, { purchase })
 export type SetPurchaseAction = ReturnType<typeof setPurchase>
+
+// Unset Purchase
+export const UNSET_PURCHASE = 'Unset Purchase'
+export const unsetPurchase = (purchase: Purchase) =>
```
Comment (fzavalia) [inline src/modules/mana/actions.ts:12]: Add a test for the action

**Review by fzavalia — CHANGES_REQUESTED** [review]
Add tests 🙏

**Review by fzavalia — APPROVED** [review]
Great ❤️
